#!/bin/bash

CASSANDRA_DOCKER_IMAGE=cassandra:2.1.15

docker run \
    --name=cqlsh \
    --network=host \
    --volume=$(pwd):/cql:ro \
    --workdir=/cql \
    --rm -it "$CASSANDRA_DOCKER_IMAGE" cqlsh "$@"
