version: '2'
services:
    cassandra:
        container_name: cassandra
        image: cassandra:2.1.15
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            # - 9160:9160
        volumes:
            - ~/volumes/cassandra:/var/lib/cassandra
        network_mode: 'bridge'
