os:
  - linux
services:
  - docker
env:
  matrix:
    - APP=cassandra/2.1.15
    - APP=mysql/5.7.13

before_install:
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
install:
  - docker version
  - docker-compose version
script:
  - chmod +x _travis/run-tests.sh
  - ./_travis/run-tests.sh
