version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce:11.0.0-rc9.ce.0
    container_name: gitlab
    ports:
      - "20080:80"
      - "20443:443"
      - "20022:22"
    volumes:
      - ~/volumes/gitlab/config:/etc/gitlab
      - ~/volumes/gitlab/logs:/var/log/gitlab
      - ~/volumes/gitlab/data:/var/opt/gitlab 
  jenkins:
    image: jenkins/jenkins:2.127
    container_name: jenkins
    ports:
      - "28080:8080"
    volumes:
      - ~/volumes/jenkins/jenkins_home:/var/jenkins_home
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.0.1
    container_name: artifactory
    ports:
      - "28081:8081"
  sonar:
    image: sonarqube:7.1-alpine
    container_name: sonar
    ports:
      - "29000:9000"
      - "29092:9092"
