version: '2'
services:
    postgresql:
        container_name: postgresql
        image: postgres:9.5.4
        volumes:
            - ~/volumes/postgresql/:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=user
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
        network_mode: 'bridge'
