version: '2'
services:
    mysql:
        container_name: mysql
        image: mysql:5.7.13
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=
        ports:
            - 3306:3306
        volumes:
            - ~/volumes/mysql:/var/lib/mysql
        network_mode: 'bridge'
        command: mysqld --lower_case_table_names=1 --skip-ssl
